services:
  - type: web
    name: yourls-service
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: YOURLS_DB_USER
        fromService:
          name: yourls-db
          type: postgres
          property: user
      - key: YOURLS_DB_PASS
        fromService:
          name: yourls-db
          type: postgres
          property: password
      - key: YOURLS_DB_NAME
        fromService:
          name: yourls-db
          type: postgres
          property: database
      - key: YOURLS_DB_HOST
        fromService:
          name: yourls-db
          type: postgres
          property: host
      - key: YOURLS_SITE
        value: https://shan-url.onrender.com
      - key: YOURLS_USER
        value: admin
      - key: YOURLS_PASS
        value: Abc123456

databases:
  - name: yourls-db
    plan: free
